# Generated by Django 6.0.3 on 2026-03-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='owner_hearted',
            new_name='is_hearted',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reply',
        ),
        migrations.AddField(
            model_name='feedback',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback')),
            ],
        ),
    ]
