# Generated by Django 6.0.3 on 2026-03-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedbackreply_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
