# Generated by Django 6.0.3 on 2026-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usermemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemory',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
