# Generated by Django 6.0.3 on 2026-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_usermemory_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemory',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermemory',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usermemory',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
