# Generated by Django 6.0.3 on 2026-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_privatemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemory',
            name='location',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hcm', 'TP. Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ'), ('angiang', 'An Giang'), ('bacgiang', 'Bắc Giang'), ('bacninh', 'Bắc Ninh'), ('baria_vungtau', 'Bà Rịa - Vũng Tàu'), ('bentre', 'Bến Tre'), ('binhduong', 'Bình Dương'), ('binhdinh', 'Bình Định'), ('binhphuoc', 'Bình Phước'), ('camau', 'Cà Mau'), ('daklak', 'Đắk Lắk'), ('dongnai', 'Đồng Nai'), ('dongthap', 'Đồng Tháp'), ('gialai', 'Gia Lai'), ('hagiang', 'Hà Giang'), ('hanam', 'Hà Nam'), ('hatinh', 'Hà Tĩnh'), ('hungyen', 'Hưng Yên'), ('khanhhoa', 'Khánh Hòa'), ('kiengiang', 'Kiên Giang'), ('lamdong', 'Lâm Đồng'), ('laocai', 'Lào Cai'), ('longan', 'Long An'), ('namdinh', 'Nam Định'), ('nghean', 'Nghệ An'), ('ninhbinh', 'Ninh Bình'), ('quangninh', 'Quảng Ninh'), ('quangngai', 'Quảng Ngãi'), ('thanhhoa', 'Thanh Hóa'), ('thainguyen', 'Thái Nguyên'), ('other', 'Nước ngoài')], default='hanoi', max_length=50),
        ),
    ]
