# Generated by Django 5.2.12 on 2026-04-07 12:58

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_usermemory_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemory',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='avatars/'),
        ),
    ]
