# Generated by Django 5.2.12 on 2026-04-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_usermemory_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemory',
            name='location',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hcm', 'TP. Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('hue', 'Huế'), ('cantho', 'Cần Thơ'), ('tuyenquang', 'Tuyên Quang'), ('caobang', 'Cao Bằng'), ('laichau', 'Lai Châu'), ('laocai', 'Lào Cai'), ('thainguyen', 'Thái Nguyên'), ('dienbien', 'Điện Biên'), ('langson', 'Lạng Sơn'), ('sonla', 'Sơn La'), ('quangninh', 'Quảng Ninh'), ('thanhhoa', 'Thanh Hóa'), ('nghean', 'Nghệ An'), ('hatinh', 'Hà Tĩnh'), ('phutho', 'Phú Thọ'), ('ninhbinh', 'Ninh Bình'), ('hungyen', 'Hưng Yên'), ('bacninh', 'Bắc Ninh'), ('quangngai', 'Quảng Ngãi'), ('quangtri', 'Quảng Trị'), ('khanhhoa', 'Khánh Hòa'), ('daklak', 'Đắk Lắk'), ('gialai', 'Gia Lai'), ('lamdong', 'Lâm Đồng'), ('dongnai', 'Đồng Nai'), ('tayninh', 'Tây Ninh'), ('angiang', 'An Giang'), ('dongthap', 'Đồng Tháp'), ('vinhlong', 'Vĩnh Long'), ('camau', 'Cà Mau'), ('other', 'Nước ngoài')], default='hanoi', max_length=50),
        ),
    ]
